added button to frontend
ucsb-cs156-f24/proj-courses-f24-04 pull request #50
Opened 2024-11-26 21:49 UTC by michaelhu88

2024-11-27 01:53 UTC, raysujf requested changes
In AdminJobsPage, you just add a button for purge but didn't implement it. Then your entire job page is disabled in dokku.
![Screen Shot 2024-11-26 at 5 52 15 PM](https://github.com/user-attachments/assets/e40163bd-5317-482a-b954-fa751e6fb631)

Also, the localhost's storybook can't be opened by others. Please use the storybook link implemented on github.

Sorry, that should have included another PR question. But please fix it as well.

2024-11-27 02:15 UTC, raysujf approved these changes
LGTM

2024-11-27 23:16 UTC, pconrad requested changes
I'm confused—what does this button do?

2024-11-27 23:16 UTC, pconrad commented on frontend/src/main/pages/Admin/AdminJobsPage.js
> +      </div>
I'm confused.. does this button actually do anything?   A button typically has some kind of action associated with it.

This seems to be putting a button on the page that doesn't do anything at all.

Instead, it should be tied to a backend post call or delete call that actually purges the job log. 

Adding a button that doesn't do anything isn't particularly helpful.

2024-11-30 22:22 UTC, pconrad commented
Replaced by #51

2024-11-30 22:22 UTC, closed without merging